apiVersion: apps/v1
kind: Deployment
metadata:
  name: count
spec:
  replicas: 1
  selector:
    matchLabels:
      app: count
  template:
    metadata:
      labels:
        app: count
    spec:
      containers:
        - name: count
          image: index.docker.io/cage1016/ms-sample-count
          env:
            - name: QS_DB
              value: "count"
            - name: QS_DB_HOST
              value: "postgresql.default.svc.cluster.local"
            - name: QS_DB_PASS
              value: "password"
            - name: QS_DB_PORT
              value: "5432"
            - name: QS_DB_SSL_CERT
              value: ""
            - name: QS_DB_SSL_KEY
              value: ""
            - name: QS_DB_SSL_MODE
              value: ""
            - name: QS_DB_SSL_ROOT_CERT
              value: ""
            - name: QS_DB_USER
              value: "postgres"
            - name: QS_GRPC_PORT
              value: "10121"
            - name: QS_HTTP_PORT
              value: "10120"
            - name: QS_LOG_LEVEL
              value: "info"
---
kind: Service
apiVersion: v1
metadata:
  name: count
spec:
  selector:
    app: count
  ports:
    - port: 80
      name: http
      targetPort: 10120
    - port: 8000
      name: grpc
      targetPort: 10121
---
kind: Service
apiVersion: v1
metadata:
  name: count-external
  labels:
    app: count
spec:
  type: LoadBalancer
  selector:
    app: count
  ports:
    - port: 9190
      name: http
      targetPort: 10120
    - port: 9191
      name: grpc
      targetPort: 10121
